version: "3"

services:
    backend:
        build:
            context: ./backend
            dockerfile: ./docker/prod.Dockerfile
        ports:
            - "4000:4000"

    minio:
        image: minio/minio:RELEASE.2020-04-10T03-34-42Z
        volumes:
            - data:/data
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server /data
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

volumes:
    data:
